---
- name: Create directory for Nginx config
  file:
    path: /home/deniswork/Desktop/project-A/nginx/conf.d
    state: directory

- name: Deploy Nginx configuration
  template:
    src: ../templates/nginx.conf.j2
    dest: /home/deniswork/Desktop/project-A/nginx/conf.d/default.conf

- name: Copy Dockerfile for Nginx
  copy:
    src: Dockerfile
    dest: /home/deniswork/Desktop/project-A/nginx/Dockerfile



